---
apiVersion: "source.toolkit.fluxcd.io/v1"
kind: "OCIRepository"
metadata:
  name: "cilium"
  namespace: "flux-system"
spec:
  interval: "24h"
  url: "oci://quay.io/cilium/charts/cilium"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: "copy"
  ref:
    semver: "^1.19.0"
---
apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: "HelmRelease"
metadata:
  name: "cilium"
  namespace: "flux-system"
spec:
  interval: "10m"
  chartRef:
    kind: "OCIRepository"
    name: "cilium"
    namespace: "flux-system"
  releaseName: "cilium"
  targetNamespace: "kube-system"
  values:
    k8sServiceHost: "localhost"
    k8sServicePort: 7445
    ipam:
      mode: "kubernetes"
    kubeProxyReplacement: true
    securityContext:
      capabilities:
        ciliumAgent:
          - "CHOWN"
          - "KILL"
          - "NET_ADMIN"
          - "NET_RAW"
          - "IPC_LOCK"
          - "SYS_ADMIN"
          - "SYS_RESOURCE"
          - "DAC_OVERRIDE"
          - "FOWNER"
          - "SETGID"
          - "SETUID"
        cleanCiliumState:
          - "NET_ADMIN"
          - "SYS_ADMIN"
          - "SYS_RESOURCE"
    cgroup:
      autoMount:
        enabled: false
      hostRoot: "/sys/fs/cgroup"
    l2announcements:
      enabled: true
    externalIPs:
      enabled: true
