---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "rook-ceph"
---
apiVersion: "source.toolkit.fluxcd.io/v1"
kind: "HelmRepository"
metadata:
  name: "rook"
  namespace: "flux-system"
spec:
  interval: "24h"
  url: "https://charts.rook.io/release"
---
apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: "HelmRelease"
metadata:
  name: "rook"
  namespace: "flux-system"
spec:
  chart:
    spec:
      chart: "rook-ceph"
      sourceRef:
        kind: "HelmRepository"
        name: "rook"
        namespace: "flux-system"
      version: "^1.19.1"
  dependsOn:
    - name: "cilium"
      namespace: "flux-system"
  interval: "10m"
  releaseName: "rook-ceph"
  targetNamespace: "rook-ceph"
  values:
    containerSecurityContext:
      seccompProfile:
        type: "RuntimeDefault"
      allowPrivilegeEscalation: false
    ceph-csi-operator:
      controllerManager:
        manager:
          containerSecurityContext:
            seccompProfile:
              type: "RuntimeDefault"
    csi:
      enableCephfsDriver: false
      enableLiveness: true
      serviceMonitor:
        enabled: true
        interval: "60s"
