---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "spegel"
---
apiVersion: "source.toolkit.fluxcd.io/v1"
kind: "OCIRepository"
metadata:
  name: "spegel"
  namespace: "flux-system"
spec:
  interval: "24h"
  url: "oci://ghcr.io/spegel-org/helm-charts/spegel"
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: "copy"
  ref:
    semver: "^0.6.0"
---
apiVersion: "helm.toolkit.fluxcd.io/v2"
kind: "HelmRelease"
metadata:
  name: "spegel"
  namespace: "flux-system"
spec:
  chartRef:
    kind: "OCIRepository"
    name: "spegel"
    namespace: "flux-system"
  dependsOn:
    - name: "cilium"
      namespace: "flux-system"
  interval: "10m"
  releaseName: "spegel"
  targetNamespace: "spegel"
  values:
    spegel:
      containerdRegistryConfigPath: "/etc/cri/conf.d/hosts"
